name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Angular App
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
            azure_static_web_apps_api_token: scaddb3870c8903b1636ac6cac41f69ea609b15fb4d6ad90752a091baedfe74ba01-6e17ea51-a26a-40b1-a85a-7eca1b365b8c0032607034adb603
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: "upload"
            app_location: "."                            
            output_location: "dist/dashboard/browser"  
